### PR TITLE
Add an mhub listener

### PR DESCRIPTION
**Pull request by 2roy999**

### CODE REVIEW

**Review by idanstark42 — COMMENTED** [review]
Why not wrap a MhubClient or a WebSocket object?

**Comment by 2roy999** [comment]
Thought about that. but it's too much and beyond the reasonable scope of this package. I hope I would be able to get into creating a pull request to mhub making it better.

**Comment by idanstark42** [comment]
What about this PR? is it still relevant? I jsut don't remember what was hapenning here

**Comment by 2roy999** [comment]
We wanted to put a wrapper for the mhub. I think I didn't like the mhub to be in this package, probably because it's interface is non-standard like middleware, so I left it for the mhub users.

**Pull request closed without merging**
